interface IPlanetData {
  [index: number]:
  {
    planet: string,
    resume: string,
    internalStructure: string,
    surfaceGeology: string,
    rotationTime: number,
    revolutionTime: number,
    radius: number,
    averageTemp: number
  }
}

export const planetsData = [
  {
    planet: "Mercúrio",
    resume: "Mercúrio é o menor e mais interno planeta do Sistema Solar, orbitando o Sol a cada 87,969 dias terrestres. A sua órbita tem a maior excentricidade e o seu eixo apresenta a menor inclinação em relação ao plano da órbita dentre todos os planetas do Sistema Solar. Mercúrio completa três rotações em torno de seu eixo a cada duas órbitas. O periélio da órbita de Mercúrio apresenta uma precessão de 5 600 segundos de arco por século, um fenômeno completamente explicado apenas a partir do século XX pela Teoria da Relatividade Geral formulada por Albert Einstein. A sua aparência é brilhante quando observado da Terra, tendo uma magnitude aparente que varia de −2,6 a 5,7, embora não seja facilmente observado pois sua separação angular do Sol é de apenas 28,3º. Uma vez que Mercúrio normalmente se perde no intenso brilho solar, exceto em eclipses solares, só pode ser observado a olho nu durante o crepúsculo matutino ou vespertino. ",
    internalStructure: "Mercúrio é um dos quatro planetas telúricos do Sistema Solar e seu corpo é rochoso como a Terra. É o menor planeta do sistema solar, com um raio equatorial de 2 439,7 km. Mercúrio é menor até que os dois maiores satélites naturais do sistema solar, as luas Ganimede e Titã, embora seja mais massivo. O planeta é formado de aproximadamente 70% de material metálico e 30% de silicatos. Sua densidade é a segunda maior do sistema solar, de 5,427 g/cm³, um pouco menor apenas do que a terrestre, de 5,515 g/cm³.[9] Se o efeito da compressão gravitacional fosse retirado, os materiais constituintes de Mercúrio seriam mais densos, com uma densidade não comprimida de 5,3 g/cm³, contra a terrestre de 4,4 g/cm³",
    surfaceGeology: "A temperatura média da superfície de Mercúrio é de 169,35 °C (442,5 K), mas varia numa faixa de -173,15 °C (100 K) a 426,85 °C (700 K) devido à ausência de atmosfera e a um abrupto gradiente de temperatura entre o equador e os polos. O ponto subsolar alcança aproximadamente 700 K durante o periélio e então cai para 550 K durante o afélio. No lado escuro do planeta, a temperatura média é de 110 K (-163,15 °C). A intensidade da luz solar na superfície varia entre 4,59 e 10,61 vezes a constante solar (1 370 W•m−2). Apesar de as temperaturas serem em geral extremamente altas em sua superfície, as observações sugerem a presença de gelo no planeta. Os pisos de crateras profundas nos polos nunca são expostos diretamente à luz solar, e a temperatura ali permanece abaixo de 102 K, bem abaixo da temperatura média global. O gelo reflete com grande intensidade o radar, e observações do Observatório Goldstone e do VLA no início da década de 1990 revelaram a presença de áreas com grande reflexão do radar perto dos polos. Embora o gelo não seja a única causa possível dessas regiões reflexivas, os astrônomos acreditam que seja a mais provável.",
    rotationTime: 176,
    revolutionTime: 87969,
    radius: 2439.7,
    averageTemp: 122
  },
  {
    planet: "Vênus",
    resume: "Vénus (português europeu) ou Vênus (português brasileiro) (AO 1990: Vénus ou Vênus) é o segundo planeta do Sistema Solar em ordem de distância a partir do Sol, orbitando-o a cada 224,7 dias. Recebeu seu nome em homenagem à deusa romana do amor e da beleza Vénus, equivalente a Afrodite. Depois da Lua, é o objeto mais brilhante do céu noturno, atingindo uma magnitude aparente de -4,6, o suficiente para produzir sombras. A distância média da Terra a Vênus é de 0,28 AU, sendo esta a menor distância entre qualquer par de planetas. Como Vénus se encontra mais próximo do Sol do que a Terra, ele pode ser visto aproximadamente na mesma direção do Sol (sua maior elongação é de 47,8°). Vénus atinge seu brilho máximo algumas horas antes da alvorada ou depois do ocaso, sendo por isso conhecido como a estrela da manhã (Estrela-d'Alva) ou estrela da tarde (Vésper); também é chamado Estrela do Pastor.",
    internalStructure: "Sem dados sísmicos ou conhecimento do seu momento de inércia, existe pouca informação sobre a estrutura interna e a geoquímica de Vénus. Entretanto, a similaridade em tamanho e densidade entre Vénus e a Terra sugere que eles possuem uma estrutura interna similar: núcleo, manto e crosta. O núcleo de Vénus é, como o da Terra, pelo menos parcialmente líquido, porque os dois planetas têm se resfriado mais ou menos na mesma taxa. O tamanho ligeiramente menor de Vénus sugere que as pressões são significativamente menores no seu interior do que na Terra. A principal diferença entre os dois planetas é a inexistência de placas tectônicas em Vénus, provavelmente devido à superfície e manto secos. Isto resulta em uma reduzida perda de calor pelo planeta, impedindo-o de se resfriar, e é a provável explicação para a falta de um campo magnético gerado internamente.",
    surfaceGeology: "A maior parte da superfície venusiana parece ter sido formada por atividade vulcânica. Vénus tem um número de vulcões várias vezes superior ao da Terra e possui 167 enormes vulcões que têm mais de 100 km de diâmetro. O único complexo vulcânico deste tamanho na Terra é a Grande Ilha do Havaí, nos Estados Unidos. Entretanto, isto não acontece por Vénus ser vulcanicamente mais ativo que a Terra, e sim porque sua crosta é mais velha. A crosta oceânica da Terra é continuamente reciclada por subducção nas bordas das placas tectônicas e tem uma idade média de cerca de 100 milhões de anos, enquanto a idade da superfície venusiana é estimada entre 300 e 600 milhões de anos.",
    rotationTime: 224.65,
    revolutionTime: 224.7,
    radius: 6051.8,
    averageTemp: 462
  },
  {
    planet: "Terra",
    resume: "A Terra é o terceiro planeta mais próximo do Sol, o mais denso e o quinto maior dos oito planetas do Sistema Solar. É também o maior dos quatro planetas telúricos. É por vezes designada como Mundo ou Planeta Azul. Lar de milhões de espécies de seres vivos, incluindo os humanos, a Terra é o único corpo celeste onde é conhecida a existência de vida. O planeta formou-se há 4,56 bilhões de anos, e a vida surgiu na sua superfície um bilhão de anos depois. Desde então, a biosfera terrestre alterou significativamente a atmosfera e outros fatores abióticos do planeta, permitindo a proliferação de organismos aeróbicos, bem como a formação de uma camada de ozônio, a qual, em conjunto com o campo magnético terrestre, bloqueia radiação solar prejudicial, permitindo a vida no planeta. As propriedades físicas do planeta, bem como sua história geológica e órbita, permitiram que a vida persistisse durante este período. Acredita-se que a Terra poderá suportar vida durante pelo menos outros 500 milhões de anos.",
    internalStructure: "O interior da Terra, assim como o de outros planetas telúricos, é dividido em camadas definidas com base nas suas propriedades químicas e físicas (reológicas), mas ao contrário dos outros planetas telúricos tem um núcleo interno e um núcleo externo distintos. A camada exterior da Terra é uma crosta silicatada, sólida, quimicamente distinta, subjacente à qual se encontra um manto sólido altamente viscoso. A crosta está separada do manto pela descontinuidade de Mohorovičić, e a espessura da crosta varia: em média 6 km sob os oceanos e 30 a 50 km sob os continentes. A crosta e a porção fria e rígida do manto superior são coletivamente designados litosfera, e é da litosfera que estão compostas as placas tectônicas. Abaixo da litosfera encontra-se a astenosfera, uma camada de viscosidade relativamente baixa sobre a qual a litosfera se desloca. Entre as profundidades de 410 e 660 km abaixo da superfície, encontra-se uma zona de transição que separa o manto superior do manto inferior, e onde ocorrem alterações importantes na estrutura cristalina. Sob o manto, encontra-se um núcleo externo líquido de baixa viscosidade, que envolve um núcleo interno sólido. O núcleo interno pode girar a uma velocidade angular ligeiramente mais alta que o restante planeta, avançando 0,1–0,5° por ano.",
    surfaceGeology: "O relevo da superfície terrestre varia significativamente de local para local. Cerca de 70,8% da superfície terrestre está coberta por água, com grande parte da plataforma continental situada abaixo do nível do mar. A superfície submergida possui características montanhosas, incluindo um sistema de dorsal meso-oceânica global, bem como vulcões submarinos, fossas oceânicas, cânions submarinos, planaltos oceânicos e planícies abissais. Os restantes 29,2% não cobertos por água consistem de montanhas, desertos, planícies, planaltos e outras geomorfologias. As formas da superfície da Terra sofrem mudanças ao longo de períodos de tempo geológicos devido ao efeito da erosão e da tectônica. Estruturas superficiais criadas ou deformadas pela tectônica de placas estão continuamente sujeitas à meteorização causada pela precipitação, ciclos térmicos e efeitos químicos. Glaciações, erosão costeira, recifes de coral e grandes impactos de meteoritos, atuam também na alteração das formas da superfície terrestre.",
    rotationTime: 0.99,
    revolutionTime: 365.26,
    radius: 6378.1,
    averageTemp: 14
  },
  {
    planet: "Marte",
    resume: 'Marte é o quarto planeta a partir do Sol, o segundo menor do Sistema Solar. Batizado em homenagem a divindade romana da guerra, muitas vezes é descrito como o "Planeta Vermelho", porque o óxido de ferro predominante em sua superfície lhe dá uma aparência avermelhada. Marte é um planeta rochoso com uma atmosfera fina, com características de superfície que lembram tanto as crateras de impacto da Lua quanto vulcões, vales, desertos e calotas polares da Terra. O período de rotação e os ciclos sazonais de Marte são também semelhantes aos da Terra, assim como é a inclinação que produz as suas estações do ano. Marte é o lar do Monte Olimpo, a segunda montanha mais alta conhecida no Sistema Solar (a mais alta em um planeta), e do Valles Marineris, um desfiladeiro gigantesco. A suave Bacia Polar Norte, no hemisfério norte marciano, cobre cerca de 40% do planeta e pode ser uma enorme marca de impacto. Marte tem duas luas conhecidas, Fobos e Deimos, que são pequenas e de forma irregular. Estas luas podem ser asteroides capturados, semelhante ao 5261 Eureka, um asteroide troiano marciano.',
    internalStructure: "Tal como a Terra, este planeta sofreu diferenciação, o que resultou em um núcleo metálico denso sobreposto por materiais menos densos, a uma distância estimada entre 1 810 e 1 860 km. Os modelos atuais do interior do planeta implicam uma região central de cerca de 1 794 km ± 65 km de raio, composta principalmente por ferro e níquel, com cerca de 16-17% de enxofre. Este núcleo de sulfureto de ferro é parcialmente fluido e tem duas vezes a concentração dos elementos mais leves que existem no núcleo da Terra. O núcleo está envolvido por um manto de silicato que formou muitos dos acidentes tectônicos e vulcânicos do planeta, mas que parecem agora estar dormentes. Além do silício e do oxigênio, os elementos mais abundantes na crosta marciana são ferro, magnésio, alumínio, cálcio e potássio. A espessura média da crosta do planeta é cerca de 50 quilômetros, com uma espessura máxima de 125 km. A crosta terrestre, com uma média de 40 km de espessura, tem apenas um terço da densidade da crosta de Marte, considerando-se a razão dos tamanhos dos dois planetas. A sonda InSight, prevista para 2016, irá utilizar um sismógrafo para melhor determinar os modelos do interior do planeta.",
    surfaceGeology: "Marte é um planeta rochoso que consiste em minerais contendo silício e oxigênio, metais e outros elementos que normalmente compõem rocha. A superfície de Marte é composta principalmente de basalto toleítico, embora parte seja mais rica em sílica que o basalto típico e possa ser semelhantes às rochas andesíticas da Terra ou ao vidro de sílica. Regiões de baixo albedo apresentam concentrações de plagioclásios, sendo que as regiões de albedo mais baixo, ao norte, exibem concentrações superiores às normais de silicatos e de vidro de sílica. Partes das terras altas ao sul incluem quantidades detectáveis de piroxênios com alto teor de cálcio. Concentrações localizadas de hematita e olivina também foram encontradas. A maior parte da superfície está profundamente coberta por uma camada de pó de óxido de ferro (III) de textura fina.",
    rotationTime: 1.02,
    revolutionTime: 687,
    radius: 3389.5,
    averageTemp: -55
  },
  {
    planet: "Júpiter",
    resume: "Júpiter é o maior planeta do Sistema Solar, tanto em diâmetro quanto em massa, e é o quinto mais próximo do Sol. Possui menos de um milésimo da massa solar, contudo tem 2,5 vezes a massa de todos os outros planetas em conjunto. É um planeta gasoso, junto com Saturno, Urano e Netuno. Estes quatro planetas são por vezes chamados de planetas jupiterianos ou planetas jovianos, e são os quatro gigantes gasosos, isto é, que não são compostos primariamente de matéria sólida. Júpiter é composto principalmente de hidrogênio, sendo um quarto de sua massa composta de hélio, embora o hélio corresponda a apenas um décimo do número total de moléculas. O planeta também pode possuir um núcleo rochoso composto por elementos mais pesados, embora, como os outros planetas gigantes, não possua uma superfície sólida bem definida. Por causa de sua rotação rápida, de cerca de dez horas, ele possui o formato de uma esfera oblata (ele possui uma suave, mas perceptível, saliência em torno do equador). Sua atmosfera externa é visivelmente dividida em diversas faixas, em várias latitudes, resultando em turbulência e tempestades nas regiões onde as faixas se encontram. Uma dessas tempestades é a Grande Mancha Vermelha, uma das características visíveis de Júpiter mais conhecidas e proeminentes, cuja existência data pelo menos do século XVII, quando foi pela primeira vez avistada com telescópio, com ventos de até 650  km/h e um diâmetro transversal duas vezes maior do que a Terra.",
    internalStructure: "Acredita-se que Júpiter seja composto de um núcleo denso com uma mistura de elementos, circundado por hidrogênio metálico líquido com algum hélio e uma camada exterior, composta principalmente de hidrogênio molecular, mas para além deste esboço básico ainda existem dúvidas consideráveis sobre a estrutura interna do planeta. O núcleo é muitas vezes descrito como rochoso, mas sua composição em detalhes é desconhecida, bem como as propriedades destes materiais na temperatura e pressão a estas profundidades. Em 1997, a existência de um núcleo sólido foi sugerida por medições gravitacionais, indicando uma massa de 12 a 45 vezes a da Terra, ou 4% a 14% da massa jupiteriana. Modelo do interior de Júpiter, com um núcleo sólido, envolto por uma camada de hidrogênio metálico, hidrogênio líquido (verde) e pela própria atmosfera (em inglês). A presença de um núcleo durante ao menos parte da história de Júpiter foi sugerida por modelos de formação planetária, envolvendo a formação inicial de um núcleo rochoso ou gelado, suficientemente massivo para atrair gravitacionalmente o hidrogênio e o hélio presentes na nebulosa protossolar. Assumindo que tenha existido, o núcleo pode ter diminuído em tamanho à medida que correntes de convecção de hidrogênio metálico líquido quente se misturaram com o núcleo fundido e levaram o seu conteúdo para níveis mais altos no interior planetário. Um núcleo sólido pode não existir, já que as medições gravitacionais não são precisas o suficiente para negar esta possibilidade. Os resultados dos dados de Juno indicam que não há núcleo sólido. A incerteza dos modelos está ligada à margem de erro dos parâmetros medidos até agora: um dos coeficientes de rotação (J6) usados para descrever a quantidade de movimento linear do planeta, o raio equatorial e sua temperatura à pressão de 1 bar. Espera-se que a sonda Juno, que chegou em julho de 2016, aumente a precisão destes parâmetros, possibilitando melhores modelos do núcleo.",
    surfaceGeology: "A atmosfera de Júpiter é composta de 88 a 92% de hidrogênio e 8 a 12% de hélio, considerando a percentagem em volume de moléculas. Esta composição muda quando descrita em termos de massa, uma vez que uma molécula de hélio é cerca de quatro vezes mais massiva que uma de hidrogênio; com isso, a atmosfera de Júpiter é composta por aproximadamente 75% de hidrogênio e 24% de hélio em massa, sendo o 1% remanescente composto por outros elementos. O interior do planeta contém materiais mais densos, mudando a distribuição por massa para 71% de hidrogênio, 24% de hélio e 5% de outros elementos. A atmosfera contém traços de metano, vapor de água, amônia, compostos de silício, carbono, etano, sulfeto de hidrogênio, neônio, oxigênio, fosfina e enxofre. A parte externa da atmosfera contém cristais de amônia congelada. Através de testes usando infravermelho e ultravioleta, traços de benzeno e outros hidrocarbonetos também foram encontrados.",
    rotationTime: 0.41,
    revolutionTime: 4328.9,
    radius: 69911,
    averageTemp: -110
  },
  {
    planet: "Saturno",
    resume: "Saturno é o sexto planeta a partir do Sol e o segundo maior do Sistema Solar atrás de Júpiter. Pertencente ao grupo dos gigantes gasosos, possui cerca de 95 massas terrestres e orbita a uma distância média de 9,5 unidades astronômicas. Possui um pequeno núcleo rochoso, circundado por uma espessa camada de hidrogênio metálico e hélio. A sua atmosfera, também composta principalmente de hidrogênio, apresenta faixas com fortes ventos, cuja energia provém tanto do calor recebido do Sol quanto da energia irradiada de seu centro. Entretanto, estas bandas possuem aspecto pouco proeminente, com coloração que varia do marrom ao amarelado, devido à espessa névoa que envolve o planeta, além das camadas de nuvens. Sazonalmente surgem grandes sistemas de tempestades, além de vórtices permanentes existentes nos polos.",
    internalStructure: "As características relativas ao interior de Saturno são obtidas através do estudo do seu campo gravitacional e magnético Além das observações das propriedades físicas do planeta, outra ferramenta importante para a inferência da estrutura interna são as equações de estado, obtidas com base em estudos de laboratório e teóricos relacionando o comportamento dos materiais quando submetidos a determinada pressão e temperatura. A baixa densidade do planeta indica que o hidrogênio é o seu principal constituinte. Em sua camada atmosférica é encontrado como gás, mas conforme a pressão aumenta em direção em seu interior, o gás passa para o estado líquido quando a pressão atinge 1 quilobar, a uma profundidade de 1 000 km em relação às nuvens, onde a temperatura chega a 730 °C. Ainda mais abaixo, a pressão faz com que o hidrogênio molecular líquido se torne ainda mais denso até a uma profundidade de 20 000 km, correspondente a um terço do raio do planeta. Na metade do raio, estima-se que a pressão seja grande o suficiente para que o as moléculas de hidrogênio líquido passem para um estado eletrônico degenerado de prótons e elétrons ionizados, tornando-se hidrogênio metálico, a uma temperatura de mais de 5700 °C.",
    surfaceGeology: "Assim como a atmosfera dos demais gigantes gasosos, a atmosfera de Saturno é composta primariamente por hidrogênio (96,3%) e hélio (3,25%), além de pequenas quantidades de metano (0,45%) e amônia (0,01%) e traços de outros hidrocarbonetos. No entanto percebe-se que a abundância de hélio é consideravelmente menor em relação a Júpiter, apesar de seus tamanhos consideráveis, o que é atribuído ao fato de que o hélio, por ser mais pesado, afundou para as camadas internas do planeta, tornando a atmosfera excepcionalmente rica em hidrogênio. Principais camadas de nuvens da atmosfera de Saturno. Cores fantasiosas e alturas estimadas. A troposfera é a camada onde se desenvolvem os principais fenômenos atmosféricos, inclusive a formação de camadas de nuvens com diferentes composições, de acordo com a pressão atmosférica. Não há um limite inferior definido onde começa a camada atmosférica pelo fato de que não há uma fronteira que determine quando o hidrogênio passa a se comportar como líquido ou como gás. Desta forma, Saturno não apresenta uma superfície definida. Na estratosfera, logo acima da troposfera, onde os gases são mais rarefeitos, um dos fenômenos característicos é a fotólise do metano, causada pela radiação ultravioleta emitida pelo Sol. Como resultado, formam-se vários hidrocarbonetos mais pesados que caem e se misturam aos componentes da troposfera. Acima encontra-se a ionosfera, formada por íons resultantes da interação das partículas do vento solar e o campo magnético do planeta.",
    rotationTime: 0.44,
    revolutionTime: 167.25,
    radius: 58232,
    averageTemp: -138
  },
  {
    planet: "Urano",
    resume: 'Urano (Úrano em Portugal) é o sétimo planeta a partir do Sol, o terceiro maior e o quarto mais massivo dos oito planetas do Sistema Solar. Foi nomeado em homenagem ao deus grego do céu, Urano. Embora seja visível a olho nu em boas condições de visualização, não foi reconhecido pelos astrônomos antigos como um planeta devido a seu pequeno brilho e lenta órbita. William Herschel anunciou sua descoberta em 13 de março de 1781, expandindo as fronteiras do Sistema Solar pela primeira vez na história moderna. Urano foi também o primeiro planeta a ser descoberto por meio de um telescópio. Urano tem uma composição similar à de Netuno, e ambos possuem uma composição química diferente da dos maiores gigantes gasosos, Júpiter e Saturno. Como tal, os astrônomos algumas vezes os colocam em uma categoria separada, os "gigantes gelados". A atmosfera de Urano, embora similar às de Júpiter e Saturno em sua composição primária de hidrogênio e hélio, contém mais "gelos" tais como água, amônia e metano, assim como traços de hidrocarbonetos. É a mais fria atmosfera planetária no Sistema Solar, com uma temperatura mínima de 49 K (–224 °C). Tem uma complexa estrutura de nuvens em camadas, e acredita-se que a água forma as nuvens mais baixas, e o metano as mais exteriores. Em contraste, seu interior é formado principalmente por gelo e rochas.',
    internalStructure: "A massa de Urano é de aproximadamente 14 vezes a terrestre, tornando-o o menos massivo dos planetas gigantes. Seu diâmetro é um pouco maior que o de Netuno e aproximadamente quatro vezes o terrestre, resultando em uma densidade de 1,27 g/cm3 que o faz o segundo planeta menos denso, atrás de Saturno. Este valor indica que ele é feito primariamente de gelos, tais como água, amônia e metano. A massa total de gelo no interior do planeta não é conhecida com precisão, visto que valores diferentes aparecem dependendo do modelo escolhido; deve estar entre 9,3 e 13,5 massas terrestres. Hidrogênio e hélio constituem uma pequena parte do total, entre 0,5 e 1,5 massas terrestres. O restante da massa que não é gelo (de 0,5 a 3,7 massas terrestres) é considerado material rochoso.",
    surfaceGeology: "Embora não exista uma superfície sólida bem definida no interior de Urano, a parte mais externa da camada gasosa que é acessível ao sensoriamento remoto é chamada de atmosfera. O sensoriamento remoto consegue penetrar até aproximadamente 300 km abaixo da pressão de nível de 1 bar (100 kPa), com uma pressão correspondente por volta de 100 bar (10 MPa) e temperatura de 320 K. A tênue coroa da atmosfera se estende consideravelmente até dois raios planetários a partir da superfície nominal de 1 bar de pressão. A atmosfera uraniana pode ser dividida em três camadas: a troposfera, entre as altitudes de −300 e 50 km com pressão de 100 a 0,1 bar; a estratosfera, atravessando altitudes entre 50 e 4 000 km e pressões entre 0,1 e 10−10 bar; e a termosfera/coroa estendendo-se de uma altitude de 4 000 km a vários raios a partir da superfície nominal de 1 bar de pressão. Ao contrário da atmosfera terrestre, a uraniana não possui mesosfera.",
    rotationTime: 0.75,
    revolutionTime: 30660,
    radius: 25362,
    averageTemp: -224
  },
  {
    planet: "Netuno",
    resume: "Netuno (pt-BR) ou Neptuno (pt) (AO 1990: Netuno ou Neptuno) é o oitavo planeta do Sistema Solar, o último a partir do Sol desde a reclassificação de Plutão para a categoria de planeta anão, em 2006. Pertencente ao grupo dos gigantes gasosos, possui um tamanho ligeiramente menor que o de Urano, mas maior massa, equivalente a 17 massas terrestres. Netuno orbita o Sol a uma distância média de 30,1 unidades astronômicas. O planeta é formado por um pequeno núcleo rochoso ao redor do qual encontra-se uma camada formada possivelmente por água, amônia e metano sobre a qual situa-se sua turbulenta atmosfera, constituída predominantemente de hidrogênio e hélio. De fato, notáveis eventos climáticos ocorrem em Netuno, inclusive a formação de diversas camadas de nuvens, tempestades ciclônicas visíveis, como a já extinta Grande Mancha Escura, além dos ventos mais rápidos do Sistema Solar, que atingem mais de 2 000 km/h. A radiação solar recebida por Netuno não seria suficiente para fornecer tamanha energia à turbulenta atmosfera, pelo que descobriu-se que o calor irradiado do centro do planeta possui um papel importante na manutenção destes eventos meteorológicos extremos. A pequena quantidade de metano nas camadas altas da atmosfera é, em parte, responsável pela coloração azul do planeta. Ao redor de Netuno orbitam quatorze satélites naturais conhecidos, dos quais destaca-se Tritão, de longe o maior. Um tênue e incomum sistema de anéis também existe, exibindo uma estrutura irregular com concentrações de material que formam arcos. Sua influência gravitacional afeta as órbitas de corpos menores situados além, no Cinturão de Kuiper, entrando em ressonância orbital. ",
    internalStructure: 'Juntamente com Urano, Netuno pertence à classe dos gigantes gasosos, pois possui uma grande massa de compostos voláteis que são encontrados sob a forma de gelo nas regiões longínquas do Sistema Solar. Além disso, os modelos que descrevem a composição interna dos dois planetas são bastante semelhantes entre si. Enquanto que nos dois maiores gigantes gasosos, Júpiter e Saturno, hidrogênio e hélio compõem a maior parte da massa dos planetas, em Netuno estes elementos são abundantes somente na atmosfera, cuja espessura estimada é de cinco mil quilômetros. Embora possua dimensões ligeiramente menores, Netuno possui massa maior do que a de Urano, pelo fato de que a massa específica de Netuno é de 1,64 g/cm³ em comparação com 1,3 g/cm³ de Urano.[7] Infere-se, a partir da densidade do planeta (não tão leve para ser composto por gases leves nem tão pesado para ser composto de silicatos e metais) que seja formado predominantemente por água, metano e amônia. Embora essas substâncias sejam conhecidas como "gelos", não estão necessariamente em estado sólido no interior do planeta.[8] Possivelmente estes compostos estão mais comprimidos no interior do planeta, o que aumenta sua densidade, o que poderia ser causado também pelo maior teor de compostos rochosos nas suas camadas internas.[9]',
    surfaceGeology: "O planeta mais distante do Sol pertence ao grupo dos gigantes gasosos, sendo o quarto maior do Sistema Solar, mas sua massa é superior à de Urano. Seu raio é equivalente a 3,91 raios terrestres (cerca de 24 mil quilômetros), enquanto que sua massa corresponde a 17,14 massas terrestres. Embora esteja no grupo dos gigantes gasosos, Netuno, assim como Urano, são bem mais densos e menos massivos que Júpiter e Saturno. Contudo, seu tamanho ainda é bastante superior às dimensões dos planetas telúricos. Em virtude de sua rápida rotação (cerca de 16 horas e sete minutos), o planeta possui um ligeiro achatamento. Por isso, o raio equatorial (24 764 km) é maior do que o raio polar (24340 km). A aceleração da gravidade no planeta é de 11,15 m/s2 (pouco maior que a da Terra) e a velocidade de escape é de 23,5 km/s.",
    rotationTime: 0.66,
    revolutionTime: 60225,
    radius: 24622,
    averageTemp: -245
  },
  {
    planet: "Plutão",
    resume: "Plutão, formalmente designado 134340 Plutão (símbolos: ⯓ e ♇) é um planeta anão do Sistema Solar e o nono maior e décimo mais massivo objeto observado diretamente orbitando o Sol. Originalmente classificado como um planeta, Plutão é atualmente o maior membro conhecido do cinturão de Kuiper, uma região de corpos além da órbita de Netuno. Como outros membros do cinturão de Kuiper, Plutão é composto primariamente de rocha e gelo e é relativamente pequeno, com aproximadamente um quinto da massa da Lua e um terço de seu volume. Ele tem uma órbita altamente inclinada e excêntrica que o leva de 30 a 49 UA do Sol. Isso faz Plutão ficar periodicamente mais perto do Sol do que Netuno (Neptuno). Atualmente Plutão está a 32,9 UA do Sol.",
    internalStructure: "Observações de Plutão feitas pelo telescópio Hubble estimam uma densidade entre 1,8 e 2,1 g/cm3, sugerindo uma composição interna de aproximadamente 60% de rocha e 40% de gelo. Como a decadência de minerais radioativos eventualmente iria aquecer os gelos o suficiente para as rochas se separarem deles, cientistas esperam que a estrutura interna de Plutão seja diferenciada, com o material rochoso estabilizado em um denso núcleo cercado por um manto de gelo. O diâmetro do núcleo deve ser de cerca de 1700 km, 70% do diâmetro de Plutão.[84] É possível que o aquecimento continue atualmente, criando uma camada de oceano líquido de 100 a 180 km de profundidade no núcleo. O Institute of Planetary Research do DLR calculou que a relação densidade-raio de Plutão está em uma zona de transição, junto com Tritão, e entre satélites gelados como as luas de tamanho médio de Saturno e Urano e os satélites rochosos como Europa.",
    surfaceGeology: 'A magnitude aparente média de Plutão é 15,1, aumentando para 13,65 durante o perélio.[4] Para vê-lo, é necessário um telescópio com uma abertura de pelo menos 30 cm.[73] Visto ao telescópio, ele tem aparência similar à de uma estrela e não possui disco visível devido ao seu diâmetro angular, que é de apenas 0,11"; até mesmo visto em telescópios grandes, Plutão é visto como um ponto iluminado, refletindo a luz do Sol. A distância e os atuais limites de telescópios fazem com que seja que impossível fotografar detalhes da superfície de Plutão. Os mapas mais antigos de Plutão, feitos na década de 1980, eram mapas do brilho de Plutão feitos a partir de observações de eclipses causados por sua maior lua, Caronte. Observações foram feitas com as mudanças do brilho total médio do sistema Plutão-Caronte durante os eclipses. Por exemplo, eclipsando um ponto brilhante de Plutão muda o brilho total mais do que eclipsando um ponto escuro. Processamentos por computador de muitas observações assim podem ser usados para gerar um mapa de brilho. Esse método também pode ser usado para observar mudanças no brilho ao longo do tempo.',
    rotationTime: 6.4,
    revolutionTime: 90520,
    radius: 1188.3,
    averageTemp: -230
  },
]